services:
  renovate:
    image: renovate/renovate:latest@sha256:e262ed52b23dd8c545c80faf5b1ad5c95a07b3f198888de8d7b8928f45c307c7
    container_name: renovate

    env_file:
      - .env

    volumes:
      - ./config.js:/usr/src/app/config.js

    command: ["renovate"]

    restart: unless-stopped
