name: Renovate

on:
  schedule:
    - cron: "0 3 * * *"  # tous les jours à 3h
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        run: |
          docker run --rm \
            -e RENOVATE_TOKEN=${{ secrets.RENOVATE_TOKEN }} \
            -e RENOVATE_CONFIG_FILE=config.js \
            -e LOG_LEVEL=info \
            -v ${{ github.workspace }}:/usr/src/app \
            renovate/renovate
